image:
  pullPolicy: Always

backend:
  image: "848005667877.dkr.ecr.us-east-1.amazonaws.com/ztso-backend"
  tag: "latest"
  port: 3000
  replicas: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false

frontend:
  image: "848005667877.dkr.ecr.us-east-1.amazonaws.com/ztso-frontend"
  tag: "latest"
  port: 8080
  replicas: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false

database:
  image: mysql:8.0
  port: 3306
  replicas: 1
  securityContext:
    runAsNonRoot: true
    runAsUser: 999

namespace: ztso-app
