apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztso-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/atharvahange03/zerotrust-devsecops-project
    targetRevision: ztso-devops-local-setup
    path: k8s/helm/ztso
    helm:
      valueFiles:
        - ../../argocd/values-override.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ztso-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
